// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAUtilitiesClass.cpp
// Header definition of TRAUtilitiesClass
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#include "TRAUtilitiesClass.h"
#include "CATFrmEditor.h"
#include "CATDocument.h"
#include "CATInit.h"
#include "CATBaseUnknown.h"
#include "CATIPrtContainer.h"
#include "CATISpecObject.h"
#include "CATIGSMProceduralView.h"







 
CATImplementClass( TRAUtilitiesClass,
                   Implementation, 
                   CATBaseUnknown,
                   CATNull );
 
//-----------------------------------------------------------------------------
// TRAUtilitiesClass : constructor
//-----------------------------------------------------------------------------
TRAUtilitiesClass::TRAUtilitiesClass():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// TRAUtilitiesClass : destructor
//-----------------------------------------------------------------------------
TRAUtilitiesClass::~TRAUtilitiesClass()
{
}
 
//-----------------------------------------------------------------------------
// TRAUtilitiesClass : copy constructor
//-----------------------------------------------------------------------------
TRAUtilitiesClass::TRAUtilitiesClass(TRAUtilitiesClass& original):
   CATBaseUnknown(original)
{
}
 
//-----------------------------------------------------------------------------
// TRAUtilitiesClass : equal operator
//-----------------------------------------------------------------------------
TRAUtilitiesClass& TRAUtilitiesClass::operator=(TRAUtilitiesClass& original)
{
   CATBaseUnknown::operator=(original);
   return *this;
}
 
CATIPrtContainer * TRAUtilitiesClass::GetEditor()

{

	CATFrmEditor *pEditor = NULL;

	pEditor = CATFrmEditor::GetCurrentEditor();

	CATDocument * pDocument = NULL;

	pDocument = pEditor->GetDocument();

	CATInit_var spInit = pDocument;

	CATBaseUnknown * pRootContainer = spInit->GetRootContainer("CATIPrtContainer");

	CATIPrtContainer * pPrtContainer = (CATIPrtContainer*)pRootContainer;

	return pPrtContainer;

}


void TRAUtilitiesClass::InsertInProceduralView(CATISpecObject_var &isSpecObject)
{
	CATTry
	{
		if(!isSpecObject)
			return;
		CATIGSMProceduralView_var spGSMProcView = isSpecObject;
		if(!!spGSMProcView)
		{
			spGSMProcView->InsertInProceduralView();
			isSpecObject->Update();
		}
	}
	CATCatch(CATError, pError)
	{
	}
	CATEndTry;
}
