// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAUtilitiesClass.h
// Header definition of TRAUtilitiesClass
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAUtilitiesClass_H
#define TRAUtilitiesClass_H

#include "TRAUtilitesMod.h"
#include "CATBaseUnknown.h"
#include "CATISpecObject.h"
#include "CATIPrtContainer.h"



//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href TRAUtilitiesClass constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new TRAUtilitiesClass;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRAUtilitesMod TRAUtilitiesClass: public CATBaseUnknown
{
  CATDeclareClass;

private:

	CATIPrtContainer_var spPartContainer;

  public:

	  CATIPrtContainer * GetEditor();

	  void InsertInProceduralView(CATISpecObject_var &isSpecObject);

  // Standard constructors and destructors
  // -------------------------------------
     TRAUtilitiesClass ();
     virtual ~TRAUtilitiesClass ();

  // Copy constructor and equal operator
  // -----------------------------------
  TRAUtilitiesClass (TRAUtilitiesClass &);
  TRAUtilitiesClass& operator=(TRAUtilitiesClass&);

};

//-----------------------------------------------------------------------

#endif
