// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACreateLineEdit.cpp
// Provide implementation to interface
//    CATIEdit
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#include "TRACreateLineEdit.h"
#include "TRAICreateLineClass.h"
#include "TRACreateLineStCmd.h"
#include "CATCommand.h"



 
CATImplementClass(TRACreateLineEdit,
                  DataExtension,
                  CATIEdit,
                  CreateLine );

//-----------------------------------------------------------------------------
// TRACreateLineEdit : constructor
//-----------------------------------------------------------------------------
TRACreateLineEdit::TRACreateLineEdit():
    CATIEdit()
{
}

//-----------------------------------------------------------------------------
// TRACreateLineEdit : destructor
//-----------------------------------------------------------------------------
TRACreateLineEdit::~TRACreateLineEdit()
{
}
 
// Link the implementation to its interface
// ---------------------------------------


//BOA definition
CATImplementBOA(CATIEdit,TRACreateLineEdit);

//TIE or TIEchain definitions


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATIEdit::Activate
//-----------------------------------------------------------------------------
CATCommand * TRACreateLineEdit::Activate (CATPathElement *  iPath)
{

   TRAICreateLineClass *piCreateLine = NULL;
    HRESULT rc = QueryInterface ( IID_TRAICreateLineClass, (void**) &piCreateLine);
    if ( FAILED(rc) ) 
        return NULL;
    
    // creates the edition command
    CATCommand *pCommand =  new TRACreateLineStCmd( piCreateLine );
    
    // releases useless pointer
    if ( NULL != piCreateLine )
    {
       piCreateLine->Release();
       piCreateLine = NULL ;
    }
    
    return pCommand;
}

//-----------------------------------------------------------------------------
// Implements CATIEdit::GetInPanelEditor
//-----------------------------------------------------------------------------
CATDlgFrame * TRACreateLineEdit::GetInPanelEditor ()
{

   return NULL;
}

//-----------------------------------------------------------------------------
// Implements CATIEdit::GetPanelItem
//-----------------------------------------------------------------------------
CATDlgFrame * TRACreateLineEdit::GetPanelItem (CATDialog *  iParent , const CATString &  iTitle)
{

   return NULL;
}

