// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACommandAddin.cpp
// Provide implementation to interface
//    CATIShapeDesignWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#include "TRACommandAddin.h"

#include "CATCommandHeader.h"
#include "CATIWorkbenchAddin.h"
#include "CATCmdContainer.h"
#include "CATCmdStarter.h"
#include "CATCreateWorkshop.h"



MacDeclareHeader(MyHeader);
 
CATImplementClass(TRACommandAddin,
                  DataExtension,
                  CATBaseUnknown,
                  TRAECommandAddin );
 

//-----------------------------------------------------------------------------
// TRACommandAddin : constructor
//-----------------------------------------------------------------------------
TRACommandAddin::TRACommandAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// TRACommandAddin : destructor
//-----------------------------------------------------------------------------
TRACommandAddin::~TRACommandAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIShapeDesignWorkshopAddin.h"
TIE_CATIShapeDesignWorkshopAddin( TRACommandAddin);


//Methods implementation

void TRACommandAddin::CreateCommands()

{

new MyHeader("CreateLineHdr", "TRADlgStCmdMod", "TRACreateLineStCmd", (void*)NULL, CATFrmAvailable );

}

CATCmdContainer * TRACommandAddin::CreateToolbars( )

{

	NewAccess (CATCmdContainer ,pToolbar,Toolbar);

	NewAccess (CATCmdStarter  ,pButton,Button);

	SetAccessCommand (pButton,"CreateLineHdr");


	SetAccessChild (pToolbar,pButton);

	AddToolbarView (pToolbar,1,Top);

	return pToolbar;

}