// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TRACreateLineCatalogFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent ("System", Public); 
AddPrereqComponent ("ObjectSpecsModeler", Public);
AddPrereqComponent ("ObjectModelerBase", Public);


 
// END WIZARD EDITION ZONE
