# COPYRIGHT Dassault Systemes 2022
#======================================================================
# Imakefile for module TRACreateLineCatalogMod.m
#======================================================================
#
#  Jan 2022  Creation: Code generated by the CAA wizard  Dell
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP  CATObjectSpecsModeler CATObjectModelerBase \ 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
