// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACreateLineEdit.h
// Provide implementation to interface
//    CATIEdit

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CreateLine
//EXTENSIONTYPE:	DataExtension

//    BOA: CATIEdit

//End CAA2 Wizard Generation Report
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRACreateLineEdit_H
#define TRACreateLineEdit_H

#include "TRADlgStCmdMod.h"
#include "CATIEdit.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIEdit
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRADlgStCmdMod TRACreateLineEdit: public CATIEdit

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRACreateLineEdit ();
     virtual ~TRACreateLineEdit ();

    /**
     * Implements a function from an interface.
     * @href CATIEdit#Activate
     */
     CATCommand * Activate (CATPathElement *  iPath ) ;

    /**
     * Implements a function from an interface.
     * @href CATIEdit#GetInPanelEditor
     */
     CATDlgFrame * GetInPanelEditor () ;

    /**
     * Implements a function from an interface.
     * @href CATIEdit#GetPanelItem
     */
     CATDlgFrame * GetPanelItem (CATDialog *  iParent  , const CATString &  iTitle ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRACreateLineEdit (TRACreateLineEdit &);
  TRACreateLineEdit& operator=(TRACreateLineEdit&);

};

//-----------------------------------------------------------------------

#endif
