// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAECreateLineClass.h
// Provide implementation to interface
//    TRAICreateLineClass

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CreateLine
//EXTENSIONTYPE:	DataExtension

//    TIE: TRAICreateLineClass

//End CAA2 Wizard Generation Report
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAECreateLineClass_H
#define TRAECreateLineClass_H

#include "TRACreateLineMod.h"
#include "CATBaseUnknown.h"
#include "CATISpecObject.h"


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href TRAICreateLineClass
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRACreateLineMod TRAECreateLineClass: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRAECreateLineClass ();
     virtual ~TRAECreateLineClass ();

    /**
     * Implements a function from an interface.
     * @href TRAICreateLineClass#SetPoint
     */
     HRESULT SetPoint (int  iNum   , CATISpecObject * ipiSpecOnCurve  ) ;

    /**
     * Implements a function from an interface.
     * @href TRAICreateLineClass#GetPoint
     */
     HRESULT GetPoint (int  iNum   , CATISpecObject ** opiSpecOnCurve  ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRAECreateLineClass (TRAECreateLineClass &);
  TRAECreateLineClass& operator=(TRAECreateLineClass&);

};

//-----------------------------------------------------------------------

#endif
