// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TRACreateLineFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("ObjectModelerBase",Public);
AddPrereqComponent("TRAICreateLineFWInterfaces",Public);

AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("BasicTopologicalOpe",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("ObjectModelerNavigator",Public);
AddPrereqComponent("Visualization",Public);

 

 
// END WIZARD EDITION ZONE
