# COPYRIGHT Dassault Systemes 2022
#======================================================================
# Imakefile for module TRAICreateLineFWInterfacesUUID.m
#======================================================================
#
#  Jan 2022  Creation: Code generated by the CAA wizard  Dell
#======================================================================
#
# ARCHIVE
#
BUILT_OBJECT_TYPE=ARCHIVE
