// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TRADlgStCmdFW
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("Visualization",Protected);
AddPrereqComponent("TRAUtilitiesFW",Protected);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("TRACreateLineFW",Protected);
AddPrereqComponent("TRAICreateLineFWInterfaces",Protected);
AddPrereqComponent("MechanicalModelerUI",Protected);
AddPrereqComponent("MechanicalModeler",Protected);
AddPrereqComponent("ObjectModelerNavigator",Protected);



 
// END WIZARD EDITION ZONE
