# COPYRIGHT Dassault Systemes 2022
#======================================================================
# Imakefile for module TRAICreateLineFWItf.m 
#======================================================================
#
#  Jan 2022  Creation: Code generated by the CAA wizard  Dell
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = \
    JS0GROUP CATObjectSpecsModeler   \
JS0FM TRAICreateLineFWInterfacesUUID 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

INCLUDED_MODULES = \
                  TRAICreateLineFWItfCPP \
