// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAICreateLineClass.h
// Define the TRAICreateLineClass interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAICreateLineClass_H
#define TRAICreateLineClass_H

#include "TRAICreateLineFWItfCPP.h"
#include "CATBaseUnknown.h"

#include "CATISpecObject.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByTRAICreateLineFWItfCPP IID IID_TRAICreateLineClass;
#else
extern "C" const IID IID_TRAICreateLineClass ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* TRAICreateLineClass are ...
* <p>
* Do not use the TRAICreateLineClass interface for such and such

*
* @example
*  // example is optional
*  TRAICreateLineClass* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_TRAICreateLineClass,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRAICreateLineFWItfCPP TRAICreateLineClass: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	   virtual HRESULT SetPoint ( int iNum , CATISpecObject *ipiSpecOnCurve )=0; 

	 virtual HRESULT GetPoint ( int iNum , CATISpecObject **opiSpecOnCurve ) = 0; 

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

//------------------------------------------------------------------

#endif
