// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAICreateLineFactory.h
// Define the TRAICreateLineFactory interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAICreateLineFactory_H
#define TRAICreateLineFactory_H

#include "TRAICreateLineFWItfCPP.h"
#include "CATBaseUnknown.h"
#include "CATISpecObject.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByTRAICreateLineFWItfCPP IID IID_TRAICreateLineFactory;
#else
extern "C" const IID IID_TRAICreateLineFactory ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* TRAICreateLineFactory are ...
* <p>
* Do not use the TRAICreateLineFactory interface for such and such

*
* @example
*  // example is optional
*  TRAICreateLineFactory* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_TRAICreateLineFactory,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRAICreateLineFWItfCPP TRAICreateLineFactory: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

	  virtual HRESULT CreateLine (  CATISpecObject *ipPoint1 ,
                                            CATISpecObject *ipPoint2 ,                                            
                                            CATISpecObject **opLine ) = 0 ;

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------
};

CATDeclareHandler(TRAICreateLineFactory,CATBaseUnknown);


//------------------------------------------------------------------

#endif
