// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACreateLineStCmd.h
// The state chart based command: TRACreateLineStCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jan 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRACreateLineStCmd_H
#define TRACreateLineStCmd_H

#include "TRADlgStCmdMod.h"
#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "TRADlgClass.h"
#include "CATFrmEditor.h"
#include "CATHSO.h"
#include "CATPathElementAgent.h"

#include "CATIGSMPoint.h"
#include "CATIPrtContainer.h"
#include "TRAICreateLineClass.h"
#include "CATISpecObject.h"






class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class ExportedByTRADlgStCmdMod TRACreateLineStCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TRACreateLineStCmd, CATStateCommand )

  public:

  CATDialogState * pPoint1SelectionState;
  CATDialogState * pPoint2SelectionState;

  CATPathElementAgent * pPoint1Agent;
  CATPathElementAgent * pPoint2Agent;

  CATDialogAgent * pOKAgent;
  CATDialogAgent * pCancelAgent;

  CATDialogAgent * pPoint1SelectorListAgent;
  CATDialogAgent * pPoint2SelectorListAgent;

  CATIGSMPoint_var spFirstPoint;
  CATIGSMPoint_var spSecondPoint;

  CATIPrtContainer_var spPartContainer;



  TRACreateLineStCmd(TRAICreateLineClass *_ipiCreatLine = NULL);
  virtual ~TRACreateLineStCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  private:

	  int _mode;

	  TRAICreateLineClass * _piCreatLine;

	  CATISpecObject_var      _spSpecObjOnPreviousCurrentFeat ;

	 CATISpecObject        *_piPoint1 , *_piPoint2;

	  TRADlgClass * _pWindow;
	  CATFrmEditor * _pEditor;
      CATHSO * _pCATHSO;

  void CreateLine();

  CATBoolean Exit();
  CATBoolean OK();
  CATBoolean Cancel();

  virtual CATBoolean SelectFirstPoint();
  virtual CATBoolean SelectSecondPoint();

  CATBoolean FirstPointEditorIsSelected();
  CATBoolean SecondPointEditorIsSelected();

 /* CATStatusChangeRC Activate   (CATCommand * iCmd,CATNotification * iNotif);
    CATStatusChangeRC Deactivate   (CATCommand * iCmd,CATNotification * iNotif);*/

  void CheckOKSensitivity();

  HRESULT IsCombCrvInsideOrderedBody(CATBoolean & oIsInsideOrderedBody );

  void UpdatePanelFields();

  
};

//----------------------------------------------------------------------

#endif
