# COPYRIGHT Dassault Systemes 2022
#======================================================================
# Imakefile for module TRAICreateLineFWItfCpp.m
# Module containing the C++ source included in your interface framework
#======================================================================
#
#  Jan 2022  Creation: Code generated by the CAA wizard  Dell
#======================================================================
#
# NO BUILD            
#

BUILT_OBJECT_TYPE=NONE
