// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACreateLineMf3DBehavior.h
// Provide implementation to interface
//    CATIMf3DBehavior

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CreateLine
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIMf3DBehavior

//End CAA2 Wizard Generation Report
//
//  Feb 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRACreateLineMf3DBehavior_H
#define TRACreateLineMf3DBehavior_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIMf3DBehavior
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TRACreateLineMf3DBehavior: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRACreateLineMf3DBehavior ();
     virtual ~TRACreateLineMf3DBehavior ();

    /**
     * Implements a function from an interface.
     * @href CATIMf3DBehavior#IsASolid
     */
     HRESULT IsASolid () const ;

    /**
     * Implements a function from an interface.
     * @href CATIMf3DBehavior#IsAShape
     */
     HRESULT IsAShape () const ;

    /**
     * Implements a function from an interface.
     * @href CATIMf3DBehavior#IsADatum
     */
     HRESULT IsADatum () const ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRACreateLineMf3DBehavior (TRACreateLineMf3DBehavior &);
  TRACreateLineMf3DBehavior& operator=(TRACreateLineMf3DBehavior&);

};

//-----------------------------------------------------------------------

#endif
