// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAECreateLineMechProp.h
// Provide implementation to interface
//    CATIMechanicalProperties

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	CreateLine
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIMechanicalProperties

//End CAA2 Wizard Generation Report
//
//  Feb 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAECreateLineMechProp_H
#define TRAECreateLineMechProp_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIMechanicalProperties
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TRAECreateLineMechProp: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRAECreateLineMechProp ();
     virtual ~TRAECreateLineMechProp ();

	

    /**
     * Implements a function from an interface.
     * @href CATIMechanicalProperties#IsInactive
     */
     int IsInactive () const ;

    /**
     * Implements a function from an interface.
     * @href CATIMechanicalProperties#Activate
     */
     void Activate () ;

    /**
     * Implements a function from an interface.
     * @href CATIMechanicalProperties#InActivate
     */
     void InActivate () ;


  private:

	  int _status ;

  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRAECreateLineMechProp (TRAECreateLineMechProp &);
  TRAECreateLineMechProp& operator=(TRAECreateLineMechProp&);

};

//-----------------------------------------------------------------------

#endif
